apiVersion: v1
kind: Service
metadata:
  name: ecommerce-order
spec:
  selector:
    app: ecommerce-order
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 9002
      targetPort: 9002 # HTTP
      nodePort: 30012
