apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-payments
  template:
    metadata:
      labels:
        app: ecommerce-payments
    spec:
      containers:
        - name: ecommerce-payments
          image: dickypratamss/ecommerce-payments:latest
          ports:
            - containerPort: 9003 # HTTP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"