apiVersion: v1
kind: Service
metadata:
  name: ecommerce-products
spec:
  selector:
    app: ecommerce-products
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 9001 # HTTP
      nodePort: 30011
