apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ums
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-ums
  template:
    metadata:
      labels:
        app: ecommerce-ums
    spec:
      containers:
        - name: ecommerce-ums
          image: dickypratamss/ecommerce-ums:latest
          ports:
            - containerPort: 9000 # HTTP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"