apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ums
spec:
  selector:
    app: ecommerce-ums
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 9000
      targetPort: 9000 # HTTP
      nodePort: 30010
